import { Account } from '@/types';

export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    name: "Emirates NBD Current",
    bank: "Emirates NBD",
    type: "checking",
    balance: 52000.00,
    currency: "AED",
    accountNumber: "****4567",
    isActive: true,
    connectedDate: "2023-03-15",
  },
  {
    id: "acc-2",
    name: "ADCB Savings",
    bank: "Abu Dhabi Commercial Bank",
    type: "savings",
    balance: 145000.00,
    currency: "AED",
    accountNumber: "****8901",
    isActive: true,
    connectedDate: "2023-06-20",
  },
  {
    id: "acc-3",
    name: "FAB Credit Card",
    bank: "First Abu Dhabi Bank",
    type: "credit",
    balance: -4200.00,
    currency: "AED",
    accountNumber: "****2345",
    isActive: true,
    connectedDate: "2024-02-01",
  },
  {
    id: "acc-4",
    name: "Investment Portfolio",
    bank: "EFG Hermes",
    type: "investment",
    balance: 298000.00,
    currency: "AED",
    accountNumber: "****6789",
    isActive: true,
    connectedDate: "2023-09-10",
  },
  {
    id: "acc-5",
    name: "HSBC USD Account",
    bank: "HSBC UAE",
    type: "savings",
    balance: 41000.00,
    currency: "AED",
    accountNumber: "****9012",
    isActive: true,
    connectedDate: "2024-05-15",
  },
  {
    id: "acc-6",
    name: "Toyota Land Cruiser 2023",
    bank: "Asset",
    type: "asset",
    balance: 95000.00,
    currency: "AED",
    accountNumber: "Vehicle",
    isActive: true,
    connectedDate: "2023-08-20",
  },
];