import { Budget, BudgetCategory } from '@/types';

export const mockBudgetCategories: BudgetCategory[] = [
  {
    id: "cat-1",
    name: "Groceries",
    budgetedAmount: 1500,
    spentAmount: 1245.50,
    currency: "AED",
    color: "#10b981",
    isFlexible: true,
  },
  {
    id: "cat-2",
    name: "Transportation",
    budgetedAmount: 800,
    spentAmount: 685.00,
    currency: "AED",
    color: "#3b82f6",
    isFlexible: true,
  },
  {
    id: "cat-3",
    name: "Utilities",
    budgetedAmount: 1300,
    spentAmount: 1265.00,
    currency: "AED",
    color: "#f59e0b",
    isFlexible: false,
  },
  {
    id: "cat-4",
    name: "Dining",
    budgetedAmount: 600,
    spentAmount: 445.50,
    currency: "AED",
    color: "#ef4444",
    isFlexible: true,
  },
  {
    id: "cat-5",
    name: "Shopping",
    budgetedAmount: 1000,
    spentAmount: 1350.00,
    currency: "AED",
    color: "#8b5cf6",
    isFlexible: true,
  },
  {
    id: "cat-6",
    name: "Healthcare",
    budgetedAmount: 500,
    spentAmount: 250.00,
    currency: "AED",
    color: "#06b6d4",
    isFlexible: false,
  },
];

export const mockBudgets: Budget[] = [
  {
    id: "budget-1",
    userId: "user-123",
    name: "Monthly Budget - January 2024",
    type: "category",
    period: "monthly",
    totalAmount: 18000,
    currency: "AED",
    categories: mockBudgetCategories,
    startDate: "2024-01-01",
    endDate: "2024-01-31",
    isActive: true,
  },
  {
    id: "budget-2",
    userId: "user-123",
    name: "Hajj Savings Plan",
    type: "flex",
    period: "yearly",
    totalAmount: 30000,
    currency: "AED",
    categories: [
      {
        id: "cat-hajj-1",
        name: "Travel & Accommodation",
        budgetedAmount: 25000,
        spentAmount: 0,
        currency: "AED",
        color: "#10b981",
        isFlexible: false,
      },
      {
        id: "cat-hajj-2",
        name: "Visa & Documentation",
        budgetedAmount: 3000,
        spentAmount: 1500,
        currency: "AED",
        color: "#f59e0b",
        isFlexible: false,
      },
      {
        id: "cat-hajj-3",
        name: "Shopping & Gifts",
        budgetedAmount: 2000,
        spentAmount: 0,
        currency: "AED",
        color: "#8b5cf6",
        isFlexible: true,
      },
    ],
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    isActive: true,
  },
];