import { Category, UAEBank, UAEMerchant } from '@/types';

export const mockCategories: Category[] = [
  {
    id: "cat-income",
    name: "Income",
    arabicName: "الدخل",
    icon: "💰",
    color: "#10b981",
    isUAESpecific: false,
    subcategories: [
      {
        id: "cat-salary",
        name: "Salary",
        arabicName: "الراتب",
        icon: "💼",
        color: "#10b981",
        parentId: "cat-income",
        isUAESpecific: false,
      },
      {
        id: "cat-freelance",
        name: "Freelance",
        arabicName: "العمل الحر",
        icon: "💻",
        color: "#059669",
        parentId: "cat-income",
        isUAESpecific: false,
      },
    ],
  },
  {
    id: "cat-groceries",
    name: "Groceries",
    arabicName: "البقالة",
    icon: "🛒",
    color: "#f59e0b",
    isUAESpecific: false,
    subcategories: [
      {
        id: "cat-food",
        name: "Food & Beverages",
        arabicName: "الطعام والمشروبات",
        icon: "🍎",
        color: "#f59e0b",
        parentId: "cat-groceries",
        isUAESpecific: false,
      },
      {
        id: "cat-household",
        name: "Household Items",
        arabicName: "أدوات منزلية",
        icon: "🧽",
        color: "#d97706",
        parentId: "cat-groceries",
        isUAESpecific: false,
      },
    ],
  },
  {
    id: "cat-transportation",
    name: "Transportation",
    arabicName: "المواصلات",
    icon: "🚗",
    color: "#3b82f6",
    isUAESpecific: false,
    subcategories: [
      {
        id: "cat-fuel",
        name: "Fuel",
        arabicName: "الوقود",
        icon: "⛽",
        color: "#3b82f6",
        parentId: "cat-transportation",
        isUAESpecific: false,
      },
      {
        id: "cat-salik",
        name: "Salik Tolls",
        arabicName: "رسوم سالك",
        icon: "🛣️",
        color: "#1d4ed8",
        parentId: "cat-transportation",
        isUAESpecific: true,
      },
      {
        id: "cat-metro",
        name: "Dubai Metro",
        arabicName: "مترو دبي",
        icon: "🚇",
        color: "#2563eb",
        parentId: "cat-transportation",
        isUAESpecific: true,
      },
    ],
  },
  {
    id: "cat-utilities",
    name: "Utilities",
    arabicName: "المرافق",
    icon: "⚡",
    color: "#ef4444",
    isUAESpecific: false,
    subcategories: [
      {
        id: "cat-dewa",
        name: "DEWA",
        arabicName: "هيئة كهرباء ومياه دبي",
        icon: "💡",
        color: "#ef4444",
        parentId: "cat-utilities",
        isUAESpecific: true,
      },
      {
        id: "cat-etisalat",
        name: "Etisalat",
        arabicName: "اتصالات",
        icon: "📱",
        color: "#dc2626",
        parentId: "cat-utilities",
        isUAESpecific: true,
      },
      {
        id: "cat-du",
        name: "Du",
        arabicName: "دو",
        icon: "📶",
        color: "#b91c1c",
        parentId: "cat-utilities",
        isUAESpecific: true,
      },
    ],
  },
  {
    id: "cat-dining",
    name: "Dining",
    arabicName: "الطعام",
    icon: "🍽️",
    color: "#8b5cf6",
    isUAESpecific: false,
    subcategories: [
      {
        id: "cat-restaurants",
        name: "Restaurants",
        arabicName: "المطاعم",
        icon: "🍽️",
        color: "#8b5cf6",
        parentId: "cat-dining",
        isUAESpecific: false,
      },
      {
        id: "cat-coffee",
        name: "Coffee & Tea",
        arabicName: "القهوة والشاي",
        icon: "☕",
        color: "#7c3aed",
        parentId: "cat-dining",
        isUAESpecific: false,
      },
    ],
  },
  {
    id: "cat-healthcare",
    name: "Healthcare",
    arabicName: "الرعاية الصحية",
    icon: "🏥",
    color: "#06b6d4",
    isUAESpecific: false,
    subcategories: [
      {
        id: "cat-pharmacy",
        name: "Pharmacy",
        arabicName: "الصيدلية",
        icon: "💊",
        color: "#06b6d4",
        parentId: "cat-healthcare",
        isUAESpecific: false,
      },
      {
        id: "cat-doctor",
        name: "Doctor Visits",
        arabicName: "زيارات الطبيب",
        icon: "👨‍⚕️",
        color: "#0891b2",
        parentId: "cat-healthcare",
        isUAESpecific: false,
      },
    ],
  },
];

export const mockUAEBanks: UAEBank[] = [
  {
    id: "bank-enbd",
    name: "Emirates NBD",
    arabicName: "بنك الإمارات دبي الوطني",
    logo: "/banks/enbd.png",
    supported: true,
    features: ["Cards", "Loans", "Investments", "Islamic Banking"],
  },
  {
    id: "bank-adcb",
    name: "Abu Dhabi Commercial Bank",
    arabicName: "بنك أبوظبي التجاري",
    logo: "/banks/adcb.png",
    supported: true,
    features: ["Personal Banking", "Business Banking", "Islamic Banking"],
  },
  {
    id: "bank-fab",
    name: "First Abu Dhabi Bank",
    arabicName: "بنك أبوظبي الأول",
    logo: "/banks/fab.png",
    supported: true,
    features: ["Digital Banking", "Wealth Management", "Corporate Banking"],
  },
  {
    id: "bank-adib",
    name: "Abu Dhabi Islamic Bank",
    arabicName: "مصرف أبوظبي الإسلامي",
    logo: "/banks/adib.png",
    supported: true,
    features: ["Islamic Banking", "Sharia-compliant Products", "Sukuk"],
  },
  {
    id: "bank-cbd",
    name: "Commercial Bank of Dubai",
    arabicName: "بنك دبي التجاري",
    logo: "/banks/cbd.png",
    supported: false,
    features: ["Personal Banking", "SME Banking"],
  },
];

export const mockUAEMerchants: UAEMerchant[] = [
  {
    id: "merchant-carrefour",
    name: "Carrefour",
    arabicName: "كارفور",
    category: "Groceries",
    subcategory: "Hypermarket",
    isLocal: false,
  },
  {
    id: "merchant-adnoc",
    name: "ADNOC",
    arabicName: "أدنوك",
    category: "Transportation",
    subcategory: "Fuel",
    isLocal: true,
  },
  {
    id: "merchant-dewa",
    name: "DEWA",
    arabicName: "هيئة كهرباء ومياه دبي",
    category: "Utilities",
    subcategory: "Electricity",
    isLocal: true,
  },
  {
    id: "merchant-moe",
    name: "Mall of Emirates",
    arabicName: "مول الإمارات",
    category: "Shopping",
    subcategory: "Mall",
    isLocal: true,
  },
  {
    id: "merchant-union-coop",
    name: "Union Coop",
    arabicName: "جمعية الاتحاد التعاونية",
    category: "Groceries",
    subcategory: "Supermarket",
    isLocal: true,
  },
];