import { Goal } from '@/types';

export const mockGoals: Goal[] = [
  // COMPLETED GOALS (showing success history)
  {
    id: "goal-1",
    userId: "user-123",
    name: "Emergency Fund",
    description: "Built emergency fund to cover 3 months of expenses",
    type: "savings",
    targetAmount: 65000,
    currentAmount: 65000,
    currency: "AED",
    targetDate: "2025-12-31",
    createdDate: "2024-03-01",
    priority: "high",
    isCompleted: true,
  },
  {
    id: "goal-4",
    userId: "user-123",
    name: "Family Summer Vacation 2025",
    description: "Enjoyed family vacation to Turkey and Europe",
    type: "purchase",
    targetAmount: 15000,
    currentAmount: 15000,
    currency: "AED",
    targetDate: "2025-12-01",
    createdDate: "2023-12-10",
    priority: "high",
    isCompleted: true,
  },
  {
    id: "goal-5",
    userId: "user-123",
    name: "Investment Portfolio Growth",
    description: "Grew investment portfolio beyond AED 350,000 target",
    type: "investment",
    targetAmount: 350000,
    currentAmount: 380000,
    currency: "AED",
    targetDate: "2025-10-30",
    createdDate: "2023-06-01",
    priority: "low",
    isCompleted: true,
  },

  // ACTIVE ONGOING GOALS
  {
    id: "goal-2",
    userId: "user-123",
    name: "Hajj Pilgrimage 2026",
    description: "Save for Hajj pilgrimage journey in 2026",
    type: "savings",
    targetAmount: 45000,
    currentAmount: 32500,
    currency: "AED",
    targetDate: "2026-05-15",
    createdDate: "2024-08-01",
    priority: "high",
    isCompleted: false,
    uaeSpecific: {
      type: "hajj",
    },
  },
  {
    id: "goal-7",
    userId: "user-123",
    name: "House Down Payment",
    description: "Property down payment for villa in Arabian Ranches",
    type: "purchase",
    targetAmount: 200000,
    currentAmount: 125000,
    currency: "AED",
    targetDate: "2026-03-01",
    createdDate: "2023-09-01",
    priority: "high",
    isCompleted: false,
    uaeSpecific: {
      type: "property",
    },
  },
  {
    id: "goal-6",
    userId: "user-123",
    name: "Child's Education Fund",
    description: "Save for child's international school and university",
    type: "savings",
    targetAmount: 150000,
    currentAmount: 67500,
    currency: "AED",
    targetDate: "2028-09-01",
    createdDate: "2023-05-01",
    priority: "high",
    isCompleted: false,
    uaeSpecific: {
      type: "education",
    },
  },

  // NEW 2025 GOALS
  {
    id: "goal-8",
    userId: "user-123",
    name: "Winter Vacation 2026",
    description: "Family vacation to Japan for winter holidays",
    type: "purchase",
    targetAmount: 25000,
    currentAmount: 8500,
    currency: "AED",
    targetDate: "2026-12-20",
    createdDate: "2025-07-01",
    priority: "medium",
    isCompleted: false,
  },
  {
    id: "goal-9",
    userId: "user-123",
    name: "Portfolio Expansion",
    description: "Grow investment portfolio to AED 500,000",
    type: "investment",
    targetAmount: 500000,
    currentAmount: 380000,
    currency: "AED",
    targetDate: "2026-12-31",
    createdDate: "2025-02-01",
    priority: "medium",
    isCompleted: false,
  },
  {
    id: "goal-10",
    userId: "user-123",
    name: "Car Upgrade Fund",
    description: "Save for Tesla Model Y or equivalent electric vehicle",
    type: "purchase",
    targetAmount: 180000,
    currentAmount: 45000,
    currency: "AED",
    targetDate: "2026-09-01",
    createdDate: "2025-03-15",
    priority: "low",
    isCompleted: false,
  },
];