import { Goal } from '@/types';

export const mockGoals: Goal[] = [
  {
    id: "goal-1",
    userId: "user-123",
    name: "Emergency Fund",
    description: "Build an emergency fund to cover 6 months of expenses",
    type: "savings",
    targetAmount: 108000,
    currentAmount: 45000,
    currency: "AED",
    targetDate: "2024-12-31",
    createdDate: "2024-01-01",
    priority: "high",
    isCompleted: false,
  },
  {
    id: "goal-2",
    userId: "user-123",
    name: "Hajj Pilgrimage",
    description: "Save for Hajj pilgrimage journey in 2025",
    type: "savings",
    targetAmount: 30000,
    currentAmount: 12500,
    currency: "AED",
    targetDate: "2025-06-01",
    createdDate: "2024-01-01",
    priority: "high",
    isCompleted: false,
    uaeSpecific: {
      type: "hajj",
    },
  },
  {
    id: "goal-3",
    userId: "user-123",
    name: "Pay Off Credit Card",
    description: "Clear FAB credit card debt completely",
    type: "debt",
    targetAmount: 8450.75,
    currentAmount: 2150.25,
    currency: "AED",
    targetDate: "2024-06-30",
    createdDate: "2024-01-15",
    priority: "medium",
    isCompleted: false,
  },
  {
    id: "goal-4",
    userId: "user-123",
    name: "Vacation",
    description: "Family vacation to Maldives in summer",
    type: "purchase",
    targetAmount: 4000,
    currentAmount: 0,
    currency: "AED",
    targetDate: "2024-07-01",
    createdDate: "2024-01-10",
    priority: "high",
    isCompleted: false,
  },
  {
    id: "goal-7",
    userId: "user-123",
    name: "Down Payment",
    description: "Property down payment in Dubai Marina",
    type: "purchase",
    targetAmount: 61824,
    currentAmount: 0,
    currency: "AED",
    targetDate: "2025-12-01",
    createdDate: "2024-01-01",
    priority: "high",
    isCompleted: false,
    uaeSpecific: {
      type: "property",
    },
  },
  {
    id: "goal-5",
    userId: "user-123",
    name: "Investment Portfolio Growth",
    description: "Grow investment portfolio to AED 150,000",
    type: "investment",
    targetAmount: 150000,
    currentAmount: 89650.25,
    currency: "AED",
    targetDate: "2025-01-01",
    createdDate: "2024-01-01",
    priority: "low",
    isCompleted: false,
  },
  {
    id: "goal-6",
    userId: "user-123",
    name: "Son's University Fund",
    description: "Save for son's engineering degree at AUB",
    type: "savings",
    targetAmount: 200000,
    currentAmount: 35000,
    currency: "AED",
    targetDate: "2028-09-01",
    createdDate: "2024-01-01",
    priority: "high",
    isCompleted: false,
    uaeSpecific: {
      type: "education",
    },
  },
];