import { Transaction } from '@/types';

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    accountId: "acc-1",
    amount: -125.50,
    currency: "AED",
    description: "Carrefour Hypermarket",
    merchant: "Carrefour",
    category: "Groceries",
    subcategory: "Food & Beverages",
    date: "2024-01-12",
    type: "expense",
    notes: "Weekly grocery shopping",
    tags: ["groceries", "food"],
    aiCategorized: true,
    aiConfidence: 0.95,
  },
  {
    id: "txn-2",
    accountId: "acc-1",
    amount: -85.00,
    currency: "AED",
    description: "ADNOC Petrol Station",
    merchant: "ADNOC",
    category: "Transportation",
    subcategory: "Fuel",
    date: "2024-01-11",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 0.98,
  },
  {
    id: "txn-3",
    accountId: "acc-1",
    amount: 25000.00,
    currency: "AED",
    description: "Salary Credit",
    merchant: "ABC Company LLC",
    category: "Income",
    subcategory: "Salary",
    date: "2024-01-01",
    type: "income",
    aiCategorized: true,
    aiConfidence: 1.0,
  },
  {
    id: "txn-4",
    accountId: "acc-3",
    amount: -350.00,
    currency: "AED",
    description: "Mall of Emirates",
    merchant: "Mall of Emirates",
    category: "Shopping",
    subcategory: "Clothing",
    date: "2024-01-10",
    type: "expense",
    notes: "Winter jacket",
    tags: ["clothing", "winter"],
    aiCategorized: true,
    aiConfidence: 0.87,
  },
  {
    id: "txn-5",
    accountId: "acc-1",
    amount: -65.00,
    currency: "AED",
    description: "Du Telecom Bill",
    merchant: "Du",
    category: "Utilities",
    subcategory: "Mobile",
    date: "2024-01-09",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 0.99,
  },
  {
    id: "txn-6",
    accountId: "acc-2",
    amount: 5000.00,
    currency: "AED",
    description: "Transfer from Emirates NBD",
    merchant: "Internal Transfer",
    category: "Transfer",
    date: "2024-01-08",
    type: "transfer",
    aiCategorized: false,
  },
  {
    id: "txn-7",
    accountId: "acc-1",
    amount: -45.50,
    currency: "AED",
    description: "Starbucks Coffee",
    merchant: "Starbucks",
    category: "Dining",
    subcategory: "Coffee & Tea",
    date: "2024-01-08",
    type: "expense",
    tags: ["coffee"],
    aiCategorized: true,
    aiConfidence: 0.92,
  },
  {
    id: "txn-8",
    accountId: "acc-1",
    amount: -1200.00,
    currency: "AED",
    description: "DEWA Bill Payment",
    merchant: "DEWA",
    category: "Utilities",
    subcategory: "Electricity",
    date: "2024-01-07",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 1.0,
  },
  {
    id: "txn-9",
    accountId: "acc-3",
    amount: -450.00,
    currency: "AED",
    description: "Emirates Airlines",
    merchant: "Emirates",
    category: "Travel",
    subcategory: "Flights",
    date: "2024-01-06",
    type: "expense",
    notes: "Domestic flight to Riyadh",
    tags: ["travel", "business"],
    aiCategorized: true,
    aiConfidence: 0.96,
  },
  {
    id: "txn-10",
    accountId: "acc-1",
    amount: -250.00,
    currency: "AED",
    description: "Pharmacy Plus",
    merchant: "Pharmacy Plus",
    category: "Healthcare",
    subcategory: "Pharmacy",
    date: "2024-01-05",
    type: "expense",
    tags: ["health", "medicine"],
    aiCategorized: true,
    aiConfidence: 0.89,
  },
];