import { Transaction } from '@/types';

export const mockTransactions: Transaction[] = [
  // AUGUST 2025 TRANSACTIONS
  // Salary
  {
    id: "txn-001",
    accountId: "acc-1",
    amount: 30500.00,
    currency: "AED",
    description: "Salary Credit - August 2025",
    merchant: "TechCorp UAE LLC",
    category: "Income",
    subcategory: "Salary",
    date: "2025-08-01",
    type: "income",
    aiCategorized: true,
    aiConfidence: 1.0,
  },

  // Housing & Utilities
  {
    id: "txn-002",
    accountId: "acc-2",
    amount: -6500.00,
    currency: "AED",
    description: "Dubai Marina Apartment Rent",
    merchant: "Emaar Properties",
    category: "Housing",
    subcategory: "Rent",
    date: "2025-08-05",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 1.0,
  },
  {
    id: "txn-003",
    accountId: "acc-1",
    amount: -942.80,
    currency: "AED",
    description: "DEWA Electricity & Water Bill",
    merchant: "DEWA",
    category: "Utilities",
    subcategory: "Electricity",
    date: "2025-08-07",
    type: "expense",
    notes: "High summer usage",
    aiCategorized: true,
    aiConfidence: 1.0,
  },
  {
    id: "txn-004",
    accountId: "acc-1",
    amount: -320.00,
    currency: "AED",
    description: "Du Mobile & Internet Package",
    merchant: "Du",
    category: "Utilities",
    subcategory: "Mobile",
    date: "2025-08-09",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 0.99,
  },

  // Childcare (Back to school period)
  {
    id: "txn-005",
    accountId: "acc-2",
    amount: -3200.00,
    currency: "AED",
    description: "GEMS International School - Term 1",
    merchant: "GEMS Education",
    category: "Childcare",
    subcategory: "School Fees",
    date: "2025-08-15",
    type: "expense",
    notes: "New academic year fees",
    aiCategorized: true,
    aiConfidence: 0.98,
  },

  // Back to school shopping
  {
    id: "txn-006",
    accountId: "acc-3",
    amount: -785.50,
    currency: "AED",
    description: "Noon.com School Supplies",
    merchant: "Noon",
    category: "Shopping",
    subcategory: "Education",
    date: "2025-08-12",
    type: "expense",
    notes: "School supplies & uniforms",
    tags: ["school", "education"],
    aiCategorized: true,
    aiConfidence: 0.94,
  },

  // Investment contribution
  {
    id: "txn-007",
    accountId: "acc-4",
    amount: -10000.00,
    currency: "AED",
    description: "Monthly Investment Transfer",
    merchant: "EFG Hermes",
    category: "Transfer",
    subcategory: "Investment",
    date: "2025-08-20",
    type: "transfer",
    notes: "Increased monthly investment",
    aiCategorized: false,
  },

  // SEPTEMBER 2025 TRANSACTIONS
  // Salary
  {
    id: "txn-008",
    accountId: "acc-1",
    amount: 30500.00,
    currency: "AED",
    description: "Salary Credit - September 2025",
    merchant: "TechCorp UAE LLC",
    category: "Income",
    subcategory: "Salary",
    date: "2025-09-01",
    type: "income",
    aiCategorized: true,
    aiConfidence: 1.0,
  },

  // Housing & Utilities
  {
    id: "txn-009",
    accountId: "acc-2",
    amount: -6500.00,
    currency: "AED",
    description: "Dubai Marina Apartment Rent",
    merchant: "Emaar Properties",
    category: "Housing",
    subcategory: "Rent",
    date: "2025-09-05",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 1.0,
  },
  {
    id: "txn-010",
    accountId: "acc-1",
    amount: -789.25,
    currency: "AED",
    description: "DEWA Electricity & Water Bill",
    merchant: "DEWA",
    category: "Utilities",
    subcategory: "Electricity",
    date: "2025-09-07",
    type: "expense",
    notes: "Still summer rates",
    aiCategorized: true,
    aiConfidence: 1.0,
  },

  // Groceries (current spending)
  {
    id: "txn-011",
    accountId: "acc-1",
    amount: -278.90,
    currency: "AED",
    description: "Carrefour City Centre",
    merchant: "Carrefour",
    category: "Groceries",
    subcategory: "Food & Beverages",
    date: "2025-09-15",
    type: "expense",
    notes: "Weekly grocery shopping",
    tags: ["groceries", "food"],
    aiCategorized: true,
    aiConfidence: 0.95,
  },
  {
    id: "txn-012",
    accountId: "acc-1",
    amount: -195.80,
    currency: "AED",
    description: "Lulu Hypermarket",
    merchant: "Lulu",
    category: "Groceries",
    subcategory: "Food & Beverages",
    date: "2025-09-22",
    type: "expense",
    tags: ["groceries", "bulk"],
    aiCategorized: true,
    aiConfidence: 0.94,
  },

  // Transportation
  {
    id: "txn-013",
    accountId: "acc-3",
    amount: -245.00,
    currency: "AED",
    description: "ADNOC Petrol Station",
    merchant: "ADNOC",
    category: "Transportation",
    subcategory: "Fuel",
    date: "2025-09-18",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 0.98,
  },

  // Dining & Entertainment
  {
    id: "txn-014",
    accountId: "acc-1",
    amount: -145.00,
    currency: "AED",
    description: "Burj Al Arab Afternoon Tea",
    merchant: "Burj Al Arab",
    category: "Dining",
    subcategory: "Special Occasion",
    date: "2025-09-28",
    type: "expense",
    notes: "Family celebration",
    tags: ["family", "special"],
    aiCategorized: true,
    aiConfidence: 0.92,
  },

  // OCTOBER 2025 TRANSACTIONS (Current month)
  // Salary
  {
    id: "txn-015",
    accountId: "acc-1",
    amount: 30500.00,
    currency: "AED",
    description: "Salary Credit - October 2025",
    merchant: "TechCorp UAE LLC",
    category: "Income",
    subcategory: "Salary",
    date: "2025-10-01",
    type: "income",
    aiCategorized: true,
    aiConfidence: 1.0,
  },

  // Performance Bonus
  {
    id: "txn-016",
    accountId: "acc-1",
    amount: 8500.00,
    currency: "AED",
    description: "Q3 Performance Bonus",
    merchant: "TechCorp UAE LLC",
    category: "Income",
    subcategory: "Bonus",
    date: "2025-10-02",
    type: "income",
    notes: "Quarterly performance bonus",
    aiCategorized: true,
    aiConfidence: 1.0,
  },

  // Current month expenses (partial)
  {
    id: "txn-017",
    accountId: "acc-1",
    amount: -6500.00,
    currency: "AED",
    description: "Dubai Marina Apartment Rent",
    merchant: "Emaar Properties",
    category: "Housing",
    subcategory: "Rent",
    date: "2025-10-03",
    type: "expense",
    aiCategorized: true,
    aiConfidence: 1.0,
  },

  // Recent spending
  {
    id: "txn-018",
    accountId: "acc-3",
    amount: -89.50,
    currency: "AED",
    description: "Talabat Food Delivery",
    merchant: "Talabat",
    category: "Dining",
    subcategory: "Delivery",
    date: "2025-10-02",
    type: "expense",
    tags: ["delivery", "convenience"],
    aiCategorized: true,
    aiConfidence: 0.91,
  },
  {
    id: "txn-019",
    accountId: "acc-3",
    amount: -52.00,
    currency: "AED",
    description: "Starbucks DIFC",
    merchant: "Starbucks",
    category: "Dining",
    subcategory: "Coffee & Tea",
    date: "2025-10-03",
    type: "expense",
    tags: ["coffee", "work"],
    aiCategorized: true,
    aiConfidence: 0.92,
  },

  // Goal-related transfers
  {
    id: "txn-020",
    accountId: "acc-2",
    amount: 8000.00,
    currency: "AED",
    description: "Monthly Savings Transfer",
    merchant: "Internal Transfer",
    category: "Transfer",
    date: "2025-09-30",
    type: "transfer",
    notes: "House down payment savings",
    aiCategorized: false,
  },
  {
    id: "txn-021",
    accountId: "acc-2",
    amount: 2500.00,
    currency: "AED",
    description: "Hajj Savings Transfer",
    merchant: "Internal Transfer",
    category: "Transfer",
    date: "2025-09-30",
    type: "transfer",
    notes: "Hajj 2026 savings",
    aiCategorized: false,
  },

  // Healthcare
  {
    id: "txn-022",
    accountId: "acc-5",
    amount: -385.00,
    currency: "AED",
    description: "American Hospital Dubai",
    merchant: "American Hospital",
    category: "Healthcare",
    subcategory: "Doctor Visit",
    date: "2025-09-25",
    type: "expense",
    tags: ["health", "checkup"],
    aiCategorized: true,
    aiConfidence: 0.89,
  },

  // Shopping
  {
    id: "txn-023",
    accountId: "acc-3",
    amount: -1250.00,
    currency: "AED",
    description: "Dubai Mall Shopping",
    merchant: "Dubai Mall",
    category: "Shopping",
    subcategory: "Clothing",
    date: "2025-09-20",
    type: "expense",
    notes: "Winter clothes for family",
    tags: ["clothing", "family", "seasonal"],
    aiCategorized: true,
    aiConfidence: 0.87,
  },

  // Investment dividend
  {
    id: "txn-024",
    accountId: "acc-4",
    amount: 1850.00,
    currency: "AED",
    description: "Investment Dividend",
    merchant: "EFG Hermes",
    category: "Income",
    subcategory: "Dividends",
    date: "2025-09-15",
    type: "income",
    notes: "Quarterly dividend",
    aiCategorized: true,
    aiConfidence: 1.0,
  },
];